### ISSUE TITLE
Apache Log4j2 2.14.1 Remote Code Execution

### ISSUE THREAD

**Issue by bergernetch** [goofball222/unifi#100]
Consider upgrading UniFi to 6.5.54.

Provides fix for a security vulnerability found in a 3rd party library (CVE-2021-44228) - Apache Log4j2 2.14.1 Remote Code Execution.

https://community.ui.com/releases/UniFi-Network-Application-6-5-54/d717f241-48bb-4979-8b10-99db36ddabe1

https://community.ui.com/questions/UniFi-Controller-security-concern-zero-day-Log4j-exploit/007103a6-823b-4316-ae76-17942539208c#answer/b098ad67-22aa-42ce-9580-c0a7d91c4b89

**Comment by goofball222** [comment]
FYI I had already put in mitigation for the log4j2 issues on 2021-12-10 in 5f61aef. Latest commit 97ef850 updates the 6.5/official tag to v6.5.54. Thanks for the heads-up, the UniFi releases and "oh we'll just change the post on the community from RC to official instead of actually announcing" makes it awful to track when things change.
