### ISSUE TITLE
goofball222/unifi:sc 5.9.24 - Restart loop

### ISSUE THREAD

**Issue by woodyard** [goofball222/unifi#24]
Synology NAS running DSM 6.2-23739 Update 2
    * Docker version: 17.05.0-0379

The container goes into a restart loop when trying to run it. Reverted to previous sc-release and it starts correctly again.

**Comment by goofball222** [comment]
I'm not sure where you got 5.9.24 from on the goofball222/unifi:sc tag at this point if you pulled it from Docker Hub around the time you opened this issue. It still hasn't finished building and pushing the updated releases as of the time I'm writing this reply, so the sc tag there would still have been 5.9.22.

If you cloned the source from GitHub directly and attempted to build from there you will need to update your process due to structural changes in the repo. Dockerfiles and scripts are now named by OS and any modifications to the base software. They must now be called with a `-f Dockerfile.name` flag to `docker build` during the run, IE: `docker build -f Dockerfile.debian -t goofball222/unifi:sc .` The locations have changed as well, as all versions have been moved into their own sc, stable, etc. directories under MAJOR.MINOR dirs.

One other thing to consider: If you pulled one of the new Alpine based or -nomongo tags, there is NO internal mongodb. You have to run those in tandem with an external Mongo DB container or host instance. The README.md outlines some basics of how to do so, and the examples/docker-compose-externaldb.yml provides some further info.

If the problem persists after you've insured you're actually running the updated 5.9.24 releases please provide the following:
* Output of: `docker inspect goofball222/unifi:<tagname>`
* Output of `docker logs containername` showing it rolling through the restarts.

**Comment by woodyard** [comment]
inspect output:

[
    {
        "Id": "sha256:c3e03ab05e661fbdbf3dd726889c85c97a9592523d8a9ab54ed0c738dfaaa4b8",
        "RepoTags": [
            "goofball222/unifi:sc"
        ],
        "RepoDigests": [
            "goofball222/unifi@sha256:fe79515faa516f972f71b16c6c10227683e86cabfa4f4a772edff73f73bc7ee4"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2018-08-22T18:46:13.738587756Z",
        "Container": "082d4dd1ec30831285176696d8a81a88d6e3414f0f955d590c4a6fd701b7759f",
        "ContainerConfig": {
            "Hostname": "082d4dd1ec30",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "10001/udp": {},
                "3478/udp": {},
                "6789/tcp": {},
                "8080/tcp": {},
                "8443/tcp": {},
                "8843/tcp": {},
                "8880/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "BIND_PRIV=false",
                "DEBIAN_FRONTEND=noninteractive",
                "DEBUG=false",
                "JVM_EXTRA_OPTS=",
                "JVM_INIT_HEAP_SIZE=",
                "JVM_MAX_HEAP_SIZE=1024M",
                "PGID=999",
                "PUID=999",
                "RUN_CHOWN=true",
                "RUNAS_UID0=false"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"unifi\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:97a6ef061bed2bf1dcf88f310156ddc604015fcf54ba6d62bd52a2e111a6a155",
            "Volumes": {
                "/usr/lib/unifi/cert": {},
                "/usr/lib/unifi/data": {},
                "/usr/lib/unifi/logs": {}
            },
            "WorkingDir": "/usr/lib/unifi",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "2018-08-22T18:40:17Z",
                "org.label-schema.license": "Apache-2.0",
                "org.label-schema.name": "UniFi Controller",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "https://github.com/goofball222/unifi",
                "org.label-schema.vcs-ref": "472ab39",
                "org.label-schema.vcs-url": "https://github.com/goofball222/unifi.git",
                "org.label-schema.vendor": "The Goofball - goofball222@gmail.com",
                "org.label-schema.version": "5.9.24-64c9fed777"
            },
            "DDSM": false
        },
        "DockerVersion": "18.03.1-ee-1-tp5",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "10001/udp": {},
                "3478/udp": {},
                "6789/tcp": {},
                "8080/tcp": {},
                "8443/tcp": {},
                "8843/tcp": {},
                "8880/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "BIND_PRIV=false",
                "DEBIAN_FRONTEND=noninteractive",
                "DEBUG=false",
                "JVM_EXTRA_OPTS=",
                "JVM_INIT_HEAP_SIZE=",
                "JVM_MAX_HEAP_SIZE=1024M",
                "PGID=999",
                "PUID=999",
                "RUN_CHOWN=true",
                "RUNAS_UID0=false"
            ],
            "Cmd": [
                "unifi"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:97a6ef061bed2bf1dcf88f310156ddc604015fcf54ba6d62bd52a2e111a6a155",
            "Volumes": {
                "/usr/lib/unifi/cert": {},
                "/usr/lib/unifi/data": {},
                "/usr/lib/unifi/logs": {}
            },
            "WorkingDir": "/usr/lib/unifi",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "2018-08-22T18:40:17Z",
                "org.label-schema.license": "Apache-2.0",
                "org.label-schema.name": "UniFi Controller",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "https://github.com/goofball222/unifi",
                "org.label-schema.vcs-ref": "472ab39",
                "org.label-schema.vcs-url": "https://github.com/goofball222/unifi.git",
                "org.label-schema.vendor": "The Goofball - goofball222@gmail.com",
                "org.label-schema.version": "5.9.24-64c9fed777"
            },
            "DDSM": false
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 441493456,
        "VirtualSize": 441493456,
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:156ff16f37e49f2cb2d5eb0cf5fda53110d2f5b20872a32f5d0eca6a0e183907",
                "sha256:defc07e9ffb97beca2e53a11d8fb8b447997cb07b85e904d54c2d30de5432389",
                "sha256:511aab1318a1fc43d33969ef4a1bb0759482452c39353f7895abe5ae7ff20f0d",
                "sha256:eb75327c9536f1152f0e9fad624e7a9da960e0995765bdb15bc75cb94c24a14a",
                "sha256:352f30c33862dbb62898d1408d39c7ac7ef41e5c969190f756261f1fe0516dd0"
            ]
        }
    }
]


log:
usermod: no changes
groupmod: GID '100' already exists
[2018-08-22 19:07:15,282] <docker-entrypoint> INFO - Script version 0.6.3-debian
[2018-08-22 19:07:15,285] <docker-entrypoint> INFO - Checking system.properties setup for container
[2018-08-22 19:07:15,288] <docker-entrypoint> INFO - Existing '/usr/lib/unifi/data/system.properties' found, ensuring container mode options are enabled
[2018-08-22 19:07:15,319] <docker-entrypoint> WARN - SSL: missing '/usr/lib/unifi/cert/privkey.pem', cannot update certificate in '/usr/lib/unifi/data/keystore'
[2018-08-22 19:07:15,326] <docker-entrypoint> WARN - SSL: missing '/usr/lib/unifi/cert/fullchain.pem', cannot update certificate in '/usr/lib/unifi/data/keystore'
[2018-08-22 19:07:15,330] <docker-entrypoint> WARN - SSL: certificate import was NOT performed
[2018-08-22 19:07:15,339] <docker-entrypoint> INFO - Entrypoint running with UID 0 (root)
[2018-08-22 19:07:15,348] <docker-entrypoint> INFO - Setting custom unifi UID/GID: UID=1026, GID=100
usermod: no changes
groupmod: GID '100' already exists
[2018-08-22 19:08:16,151] <docker-entrypoint> INFO - Script version 0.6.3-debian
[2018-08-22 19:08:16,156] <docker-entrypoint> INFO - Checking system.properties setup for container
[2018-08-22 19:08:16,160] <docker-entrypoint> INFO - Existing '/usr/lib/unifi/data/system.properties' found, ensuring container mode options are enabled
[2018-08-22 19:08:16,174] <docker-entrypoint> WARN - SSL: missing '/usr/lib/unifi/cert/privkey.pem', cannot update certificate in '/usr/lib/unifi/data/keystore'
[2018-08-22 19:08:16,177] <docker-entrypoint> WARN - SSL: missing '/usr/lib/unifi/cert/fullchain.pem', cannot update certificate in '/usr/lib/unifi/data/keystore'
[2018-08-22 19:08:16,180] <docker-entrypoint> WARN - SSL: certificate import was NOT performed
[2018-08-22 19:08:16,187] <docker-entrypoint> INFO - Entrypoint running with UID 0 (root)
[2018-08-22 19:08:16,196] <docker-entrypoint> INFO - Setting custom unifi UID/GID: UID=1026, GID=100
usermod: no changes
groupmod: GID '100' already exists


run command:
sudo docker run -d \
    --name=unifi \
    -v /volume1/henrik/docker/unifi/data:/usr/lib/unifi/data  \
    -v /volume1/henrik/docker/unifi/logs:/usr/lib/unifi/logs \
    -v  /volume1/henrik/docker/unifi/svlogs:/var/log/supervisor \
    -v /volume1/henrik/docker/unifi/cert:/usr/lib/unifi/cert \
    -e PGID=100 -e PUID=1026  \
    --net="host" \
    --restart="always" \
    goofball222/unifi:sc

**Comment by goofball222** [comment]
Thank you, that is extremely helpful in pinpointing the issue.

You're setting `-e PGID=100` in your run command, which wasn't anything the container was parsing up until https://github.com/goofball222/unifi/commit/36528c20cfd6872ba2de3b417d85f8817908aa37 committed on 2018-08-14. Prior to that the internal GID and UID variables were UNIFI_GID and UNIFI_UID. The sc container you have cached for 5.9.22 was built on 2018-08-08, before the PGID/PUID changes. 

On to why it's failing now, the GID 100 is already in use inside the container /etc/group for the Debian default "users" group. When the entrypoint script tries to change the container internal "docker" group GID to 100 it errors out since that GID is already in use:
```
[2018-08-22 19:08:16,196] INFO - Setting custom unifi UID/GID: UID=1026, GID=100
usermod: no changes
groupmod: GID '100' already exists
```
A quick fix for you for now is to remove PGID from your run command so it remains at the internal default of '999'.

Beyond that I need to come up with an acceptable method to run the UniFi software processes with a GID/UID that already exist in the Debian/Alpine base defaults...

**Comment by goofball222** [comment]
Fix was simpler than I thought. Docker Hub should have rebuilt images up in ~1 hour after the time of this message that allow the container to run even when set with an in-container existing UID/GID. Added the `-o` flag to the groupmod and usermod commands - `allow to use a duplicate (non-unique) GID/UID`
