### ISSUE TITLE
Guest portal preview broken

### ISSUE THREAD

**Issue by pitah81** [goofball222/unifi#31]
OS/distribution version (command for your OS may differ): Ubuntu Server 18.04LTS
Docker version 18.09.0, build 4d60db4
Labels from container: goofball222/unifi:latest and goofball222/unifi:unifi56

Guest portal preview is broken both in Chrome and Firefox. According to some threads in the official Ubiquiti forums, it could have to do with the version of Java included in the docker image. Could it be that Java 8u151 included?

https://community.ubnt.com/t5/UniFi-Wireless/Guest-Portal-Preview/td-p/1699481
https://community.ubnt.com/t5/UniFi-Wireless/Desktop-Preview-of-Guest-Portal-Broken/td-p/2201034

**Comment by goofball222** [comment]
The image uses OpenJDK-JRE that targets Java version 8 at the latest available patchlevel package for each OS base image:
Alpine:
```
bash-4.4# java -version
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (IcedTea 3.11.0) (Alpine 8.201.08-r0)
OpenJDK 64-Bit Server VM (build 25.201-b08, mixed mode)
```
Debian:
```
root@3753e1697ca8:/usr/lib/unifi# java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

The bug you referenced was in Java 8u151 and fixed in 8u162+.

I tested this on my own instance of the controller running in Docker and I'm not seeing any problems viewing the Angular.js guest portal preview in either Chrome or FireFox.

Does this happen on a fresh controller instance with a clean data folder and DB?

**Comment by nicedevil007** [comment]
Hey goofball222, 

got it too now. The Guestportal shows me: 

![image](https://user-images.githubusercontent.com/17103076/61188476-d4a2b080-a67f-11e9-97d3-ca57b89b1fcc.png)

What is wrong? I'm using the testing tag now and did a fresh install with the standard yaml (including mongo db).

**Comment by pitah81** [comment]
I figured out that when I'm accessing the controller behind my Traefik reverse proxy on port 443 which redirects to port 8443 on the controller I get this error in displaying the guest portal preview. However if I access the controller directly using 8443 it works. Could it be that the preview window is hardcoded to port 8443?
