### ISSUE TITLE
Just small problem... How can I run the testing version with 5.11.31?

### ISSUE THREAD

**Issue by nicedevil007** [goofball222/unifi#38]
I would like to use a docker-compose.yml for that. But I can't get it to work.
Where should I paste the testing tag?

**Comment by goofball222** [comment]
Based on my example [docker-compose.yml](https://github.com/goofball222/unifi/blob/master/examples/docker-compose.yml) file change
```
...
services:
  unifi:
    image: goofball222/unifi
    container_name: unifi
...
```
to
```
...
services:
  unifi:
    image: goofball222/unifi:testing
    container_name: unifi
...
```
Keep in mind that you will need to update your docker-compose.yml to point to the correct tags as the versions evolve through unstable, testing, sc, and then to stable releases. The container releases follow the same tags Ubiquiti uses for their releases. The current "stable" release is the latest/base tag for the container.

Also keep in mind that due to software/database changes you can't directly downgrade from a newer version to older version. Make sure you have a full backup before making any version updates or tag switches.
