### ISSUE TITLE
Refactor Dockerfile to reuse layer

### ISSUE THREAD

**Issue by mkjaer** [goofball222/unifi#5]
Have you considered moving:

```  wget -nv https://www.ubnt.com/downloads/unifi/$UNIFI_VERSION/unifi_sysvinit_all.deb && \
  dpkg --install unifi_sysvinit_all.deb && \
  rm unifi_sysvinit_all.deb && \
```

To another RUN block after the other?

Doing that would make the first layer reusable between builds and versions. That would minimize disk usage if we have more than one version and it will reduce pull time on upgrades.

The downside is `apt-get -y autoremove wget` wouldn't help reduce size and as such the final size might be a couple MB larger.

**Comment by goofball222** [comment]
I'll take a look, thank you for the suggestion.

**Comment by psi-4ward** [comment]
Having multiple versions on same docker host is very unusual, isnt it?

**Comment by goofball222** [comment]
@psi-4ward It would be in my use cases and most others I can think of. The only reason I've built as many different tags/branches as I have is to try to match what Ubiquiti does for their releases and allow other users the option to choose what they need. However with that said: to each their own, just because I don't use my personal setup that way doesn't mean someone else can't...

After looking at it I don't see any good way right now to move the Unifi install to another layer in the container AND keep the overall space down/tools removed/attack vector minimized. I'd either have to leave wget and the 3 other packages it needs installed or eat the space lost to having unifi_sysvinit_all.deb or the APT cache stuck in an earlier layer. It might be possible with duplicate effort... It's Monday morning and I'm still on my first cup of coffee, let me ponder further.

**Comment by ruimarinho** [comment]
> Having multiple versions on same docker host is very unusual, isnt it?

This is not related to docker host versions in any way. What @mkjaer is suggesting is creating another layer for the installation of dependencies. If the image has been downloaded by the same docker host before, it would only need to download the new image layer corresponding to the dynamic parts  - the `$UNIFI_VERSION` block. 

The downside is that we don't get updated dependencies on each build unless @goofball222 builds without cache. In that case, the layer cache advantage would be gone anyway. There's also the side-effect of increased image size, as the `apt-get -y autoremove` command would actually contribute to increase the image size (another layer).

All in all, I would keep this as is as there seems to be only ~1  stable release/month.

**Comment by psi-4ward** [comment]
If its all about size you should take a look at alpine linux base image

**Comment by rogierlommers** [comment]
Since it's working fine now and it's not like we do daily deployments.
Please leave it as is :).
Op ma 20 mrt. 2017 om 22:05 schreef Christoph Wiechert <
notifications@github.com>

**Comment by mkjaer** [comment]
> All in all, I would keep this as is as there seems to be only ~1 stable release/month.

The latest tag seem to be updated a lot more often than it should with almost weekly releases and having terrible internet routing this download is sometimes taking me an hour.

I tried building it by just moving those 3 unifi related lines to a new layer and not deleting wget and the outcome is this:
```
unifi                                                2layers                                             e84abafe5d0e        4 seconds ago       685 MB
unifi                                                original                                            a066d52adb1d        59 minutes ago      652 MB
```

Anyway, I don't have a strong opinion about this, but I'm happy it was discussed.

**Comment by goofball222** [comment]
The regular "latest" image updates are due to Docker hub automatically rebuilding every time anything changes on the github side, even if it's just the README.md. Unfortunately that means every time I update for a new version on any of the branches and adjust the README across the board everything that's not a tagged release regenerates. On the plus side that means if you're using an untagged release you're getting an image with the latest Debian:jessie base and all the most recent security fixins. 

I may take another look at Alpine for the base, however last time I started down that path it ended up kaput due to Java challenges. Anything along those lines would end up as another branch.

Appreciate all the input, glad there are others finding this container useful!
