### ISSUE TITLE
Why does 6.0 not have the latest tag?

### ISSUE THREAD

**Issue by zilexa** [goofball222/unifi#71]
Just wondering why the latest tag is still on the older Unifi version.

**Comment by benwiggins** [comment]
As mentioned in the CHANGELOG there’s been a number of issues with 6.0, including some nasty broadcast storms.

**Comment by goofball222** [comment]
6.0 isn't currently ready for prime-time, despite Ubiquiti tagging it as "stable". Since the "latest" tag is the default in Docker when someone/something runs `docker pull goofball222/unifi` for an install or update it needs to be functional.

Once UI has baked 6.0 for a bit longer and isn't dropping SC/RC->stable emergency releases every couple of days I'll look at moving it to "latest" on this image.
