### ISSUE TITLE
Unifi 6.5.53 stable Release

### ISSUE THREAD

**Issue by itsFlake** [goofball222/unifi#99]
Hey,
Version 6.5.53 is out now as stable. 
https://community.ui.com/releases/UniFi-Network-Application-6-5-53/16025ec1-4bbc-46a9-8f4f-8561fd59cd4c

**Comment by goofball222** [comment]
Thanks for the heads-up! UI just removes the "release candidate" tags on the posts instead of announcing anything officially. It makes it hard to track when things actually change from RC to official.

I just looked through the thread and see UI-Glenn made a post where it was promoted on Monday - https://community.ui.com/releases/UniFi-Network-Application-6-5-53/16025ec1-4bbc-46a9-8f4f-8561fd59cd4c#comment/97875559-af42-4166-9c60-8a919625efef

I'll get things updated and moved around and a release built shortly.
